Add chgrp to build_containers & check if group is correct to opencode wrapper

diff --git a/bin/roihu/opencode/opencode b/bin/roihu/opencode/opencode
--- a/bin/roihu/opencode/opencode
+++ b/bin/roihu/opencode/opencode
@@ -70,7 +70,11 @@ done
 # modified with an env variable. Therefore we must copy the skills to a valid location.
 tmp="${AGENT_IMAGE%/*}"
 BASE_OF_AGENT_ENV="${tmp%/*}"
-chgrp -R project_2001659 "$BASE_OF_AGENT_ENV/config/opencode/skills"
+config_owner="$(stat -c %G "${BASE_OF_AGENT_ENV}/config/opencode/skills")"
+if [[ $config_owner == "pepr_ansoneli" ]]; then
+    echo "ERROR: wrong group owner for skills-dir. run build_containers.sh first." >&2
+    exit 1
+fi
 rsync -r "$BASE_OF_AGENT_ENV/config/opencode/skills" "$HOME/.config/opencode/"
 
 # AGENT_IMAGE is set by the module.
